require:
  - rubocop-minitest
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
Style/AccessorGrouping:
  EnforcedStyle: separated
Layout/LineLength:
  Max: 80
Metrics/ClassLength:
  Max: 150
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
